"""Initial migration.

Revision ID: 4b3c1b22bf90
Revises: d96391e79480
Create Date: 2022-11-29 16:03:38.132411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b3c1b22bf90'
down_revision = 'd96391e79480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('persona', sa.Column('user_id', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'persona', 'user', ['user_id'], ['id'])
    op.drop_column('persona', 'tipo_usuario')
    op.drop_column('persona', 'password')
    op.drop_column('persona', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('email', mysql.TEXT(), nullable=False))
    op.add_column('persona', sa.Column('password', mysql.TEXT(), nullable=False))
    op.add_column('persona', sa.Column('tipo_usuario', mysql.VARCHAR(length=1), nullable=False))
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_column('persona', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
