"""Initial migration.

Revision ID: 5cc959e14669
Revises: 
Create Date: 2022-12-11 14:17:13.676464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc959e14669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binarios_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foto_perfil', sa.LargeBinary(), nullable=True),
    sa.Column('foto_documento', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trimestre', sa.Text(), nullable=False),
    sa.Column('fuerza_general', sa.Integer(), nullable=False),
    sa.Column('brazos', sa.Integer(), nullable=False),
    sa.Column('piernas', sa.Integer(), nullable=False),
    sa.Column('abdomen', sa.Integer(), nullable=False),
    sa.Column('resistencia_fuerza', sa.Integer(), nullable=False),
    sa.Column('resistencia_vueltas', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('resistencia_fuerzaG', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('binarios_usuarios')
    # ### end Alembic commands ###
