"""Initial migration.

Revision ID: bef58f33c8cd
Revises: 
Create Date: 2022-11-07 13:15:10.242597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef58f33c8cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=False)
    op.create_table('topos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('apellido', sa.String(length=45), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_producto')
    )
    op.create_index(op.f('ix_topos_apellido'), 'topos', ['apellido'], unique=False)
    op.create_index(op.f('ix_topos_nombre'), 'topos', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topos_nombre'), table_name='topos')
    op.drop_index(op.f('ix_topos_apellido'), table_name='topos')
    op.drop_table('topos')
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    op.drop_table('producto')
    # ### end Alembic commands ###
