"""Initial migration.

Revision ID: d96391e79480
Revises: adb20a7effd6
Create Date: 2022-11-10 23:19:02.170790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96391e79480'
down_revision = 'adb20a7effd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binarios_usuarios', sa.Column('persona_id', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'binarios_usuarios', ['persona_id'])
    op.create_foreign_key(None, 'binarios_usuarios', 'persona', ['persona_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'binarios_usuarios', type_='foreignkey')
    op.drop_constraint(None, 'binarios_usuarios', type_='unique')
    op.drop_column('binarios_usuarios', 'persona_id')
    # ### end Alembic commands ###
