"""Initial migration.

Revision ID: e83b9147551d
Revises: 9ed73184048d
Create Date: 2022-12-12 17:21:57.591963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83b9147551d'
down_revision = '9ed73184048d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_index('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.create_index('fecha', ['fecha'], unique=False)

    # ### end Alembic commands ###
